version: "3.3"
networks:
  main:

services:
  rabbitmq:
    image: rabbitmq:3
    networks:
      main:
        aliases:
        - rabbitmq
    ports:
      - target: 5672
        published: 1111
        mode: host
    environment:
    - "RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error}]"
